#!/bin/bash

# $1 - achive name

buff = ${$1:16:8}

if [ ! -f /etc/systemd/system/pub_$buff.service ]; then

    sudo touch /etc/systemd/system/pub_$buff.service

    sudo cat template >> /etc/systemd/system/pub_$buff.service

    sudo sed "s/\/home\/user\/practice\/publisher\.py/\/home\/user\/practice\/publisher\.py ${buf%%.rnx}\.rnx\/g" /etc/systemd/system/pub_$buff.service

    sudo systemctl enable /etc/systemd/system/pub_$buff.service

    sudo systemctl start pub_$buff.service
fi
