#!/bin/bash

# $1 - archive name

path=$(basename "$1")
buff=${path:0:9}

if [ ! -f /etc/systemd/system/pub_$buff.service ]; then

    sudo touch /etc/systemd/system/pub_$buff.service

    sudo cat template >> /etc/systemd/system/pub_$buff.service

    current_hour=$(date +%H)
    if [ $current_hour -ge 23 ]; then
        sudo sed -i "s/\/home\/user\/practice\/publisher\.py/\/home\/user\/practice\/publisher\.py ${path%%.rnx}\.rnx wait/g" /etc/systemd/system/pub_$buff.service
    else
        sudo sed -i "s/\/home\/user\/practice\/publisher\.py/\/home\/user\/practice\/publisher\.py ${path%%.rnx}\.rnx work/g" /etc/systemd/system/pub_$buff.service
    fi 
fi

sudo systemctl enable /etc/systemd/system/pub_$buff.service

sudo systemctl start pub_$buff.service
