#!/bin/bash

# Читаем дату из файла variables.txt
date=$(grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' /home/user/practice/variables.txt)

# + 1 день к дате
next_date=$(date -d "$date + 1 day" "+%Y-%m-%d")

sed -i "s/$date/$next_date/g" /home/user/practice/variables.txt

./starts $next_date
