#!/bin/bash

# $1 - date

python3 downloader.py $1

unzip "data/${1}.zip" -d "data/${1}"

for file in data/$1/*
do
    if [[ "$file" == *"crx.gz"* ]]
    then
        gunzip $file
	buf=${file%%.gz}
        ./CRX2RNX $buf
	buf=${buf%%.crx}
	buf="${buf}.rnx"
	python3 parser.py $buf
    fi
done
