#!/bin/bash

# $1 - date

# python3 downloader.py $1

# unzip "data/${1:0:4}/${1:5:5}.zip" -d "data/${1:0:4}/${1:5:5}"

for file in data/${1:0:4}/${1:5:5}/*
do
    if [[ "$file" == *"crx.gz"* ]]
    then
        gunzip $file
	buf=${file%%.gz}
        ./CRX2RNX $buf
	buf=${buf%%.crx}
	buf="${buf}.rnx"

        if grep -q 'rnx1' variables.txt; then
            mv $buf rnx2/
        else
	    if grep -q 'rnx2' variables.txt; then 
                mv $buf rnx1/
            else
		echo "rnx1" >> variables.txt
                mv $buf rnx1/
            fi
	fi

	echo $1 >> variables.txt

        buf="$(basename "$buf")"
	sudo ./create_services $buf

	break
    fi
done
