#!/bin/bash

# $1 - date

# python3 downloader.py $1

# unzip "data/${1:0:4}/${1:5:5}.zip" -d "data/${1:0:4}/${1:5:5}"

for file in data/${1:0:4}/${1:5:5}/*
do
    if [[ "$file" == *"crx.gz"* ]]
    then
        gunzip $file
	buf=${file%%.gz}
        ./CRX2RNX $buf
	buf=${buf%%.crx}
	buf="${buf}.rnx"
	sudo ./create_services $buf
    fi
done
