#!/bin/bash

# $1 - date

read -r mainpath < /home/user/practice/txt/mainpath.txt

log_file="$mainpath/logfile.txt"

log() {
    log_time=$(date +"%Y-%m-%d %H:%M:%S")
    local level=$1
    local message=$2
    echo "$log_time - $level - $message" | tee -a "$log_file"
}

log "INFO" "Скрипт change начал работу"

python3 ../python/downloader.py $1
log "INFO" "Скачан архив с данными на дату $next_date"

unzip "$mainpath/data/${1:0:4}/${1:5:5}.zip" -d "$mainpath/data/${1:0:4}/${1:5:5}"
log "INFO" "Разархивирована папка с данными на дату $next_date"

date=$(grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' $mainpath/txt/variables.txt)
log "INFO" "Записана новая дата $1 в файл variables.txt"

sed -i "s/$date/$1/g" $mainpath/txt/variables.txt


if grep -q 'rnx1' $mainpath/txt/variables.txt; then
    sed -i "s/rnx1/rnx2/g" $mainpath/txt/variables.txt
    log "INFO" "Записан rnx2 в файл variables.txt"
else
    sed -i "s/rnx2/rnx1/g" $mainpath/txt/variables.txt
    log "INFO" "Записан rnx1 в файл variables.txt"
fi

for file in $mainpath/data/${1:0:4}/${1:5:5}/*
do
    if [[ "$file" == *"crx.gz"* ]]
    then
        gunzip $file
	log "INFO" "Разархивирован файл $file"
        buf=${file%%.gz}

        $mainpath/bash/CRX2RNX $buf
	log "INFO" "Переведен в формат rnx файл $buf"
        buf=${buf%%.crx}
        buf="${buf}.rnx"

        if grep -q 'rnx2' $mainpath/txt/variables.txt; then
            mv $buf $mainpath/rnx2/
	    log "INFO" "Файл $buf перенесен в папку rnx2"
        else
            if grep -q 'rnx1' $mainpath/txt/variables.txt; then
                mv $buf $mainpath/rnx1/
		log "INFO" "Файл $buf перенесен в папку rnx1"
            fi
        fi

        buf="$(basename "$buf")"
	sudo $mainpath/bash/create_services $buf "change"
    fi
done
