#!/bin/bash

read -r mainpath < /home/user/practice/txt/mainpath.txt

log_file="$mainpath/logfile.txt"

log() {
    log_time=$(date +"%Y-%m-%d %H:%M:%S")
    local level=$1
    local message=$2
    echo "$log_time - $level - $message" | tee -a "$log_file"
}


log "INFO" "Скрипт newDay начал работу"

# Читаем дату из файла variables.txt
date=$(grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' $mainpath/txt/variables.txt)
log "INFO" "Прочитана дата из файла variables.txt: $date"


# Прибавляем к дате 1 день
next_date=$(date -d "$date + 1 day" "+%Y-%m-%d")
log "INFO" "Увеличена дата на 1 день: $next_date"

sed -i "s/$date/$next_date/g" $mainpath/txt/variables.txt


python3 $mainpath/python/downloader.py $next_date
log "INFO" "Скачан архив с данными на дату $next_date"

unzip "$mainpath/data/${next_date:0:4}/${next_date:5:5}.zip" -d "$mainpath/data/${next_date:0:4}/${next_date:5:5}"
log "INFO" "Разархивирована папка с данными на дату $next_date"

for file in $mainpath/data/${next_date:0:4}/${next_date:5:5}/*
do
    if [[ "$file" == *"crx.gz"* ]]
    then
        gunzip $file
	log "INFO" "Разархивирован файл $file"
        buf=${file%%.gz}
        $mainpath/bash/CRX2RNX $buf
	log "INFO" "Переведен в формат rnx файл $buf"
        buf=${buf%%.crx}
        buf="${buf}.rnx"

        if grep -q 'rnx1' $mainpath/txt/variables.txt; then
            mv $buf $mainpath/rnx2/
	    log "INFO" "Файл $buf перенесен в папку rnx2"
        else
            if grep -q 'rnx2' $mainpath/txt/variables.txt; then
                mv $buf $mainpath/rnx1/
		log "INFO" "Файл $buf перенесен в папку rnx1"
            fi
        fi

        buf="$(basename "$buf")"
        sudo $mainpath/bash/create_services $buf 'next'
    fi
done
